import Translation from '../models/Translation';

export const fetchTranslationsData = async () => {
    const data = [
      {
        id: 1,
        folderName: "Partisans 1941",
        title: "Partisans 1941",
        releaseYear: "2020",
        translator: "علي العجيلي", // المُعرّب
        appVersion: "1.1.05", // ضع النسخة المتوافقة هنا
        description:
          "لعبة تخفي وتكتيك في الوقت الفعلي تدور أحداثها في الجبهة الشرقية خلال الحرب العالمية الثانية. التعريب يشمل ترجمة شاملة للقوائم، المهام، وحوارات الشخصيات لضمان تجربة لعب متكاملة ومفهومة باللغة العربية.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط (7z) من الزر أدناه.",
          "استخدم برنامج WinRAR أو 7-Zip لفك الضغط عن الملف.",
          "انسخ جميع الملفات الناتجة والصقها داخل مجلد اللعبة الرئيسي.",
          "وافق على استبدال الملفات عند ظهور النافذة.",
          "شغل اللعبة واستمتع بالتجربة العربية!",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
          "7.webp",
        ],
        technologies: ["توطين النصوص", "تعديل الخطوط"],
        downloadFile: "Partisans1941-Arabic-Patch.7z",
        addedDate: "2026-07-29",
      },
      {
        id: 2,
        folderName: "Hollow Knight Silksong",
        title: "Hollow Knight: Silksong",
        releaseYear: "2025",
        translator: "علي العجيلي", // المُعرّب
        appVersion: "1.0.29909", // أخذت رقم النسخة من اسم ملف الـ rar الذي أرفقته
        description:
          "تعريب شامل للعبة المنتظرة Hollow Knight: Silksong. تم العمل على ترجمة الحوارات، القوائم، والأوصاف بدقة عالية مع الحفاظ على روح القصة والأسماء لتناسب سياق عالم اللعبة الساحر.",
        installationSteps: [
          "قم بتحميل ملف التعريب (rar) من الزر أدناه.",
          "قم بفك الضغط عن الملف باستخدام برنامج WinRAR.",
          "تأكد من تواجد بيئة BepInEx الأساسية في مجلد اللعبة.",
          "انسخ ملفات التعريب المستخرجة والصقها داخل مسار اللعبة الرئيسي.",
          "شغل اللعبة واستمتع بالمغامرة باللغة العربية!",
        ],
        coverImage: "poster.webp",
        screenshots: ["1.webp", "2.webp", "3.webp", "4.webp", "5.webp"],
        technologies: ["BepInEx", "Harmony", "توطين النصوص"],
        downloadFile: "Hollow-Knight-Silksong-v1.5-Arabic-Patch.rar",
        addedDate: "2026-07-11",
      },
      {
        id: 3,
        folderName: "Gothic 1 Remake",
        title: "Gothic 1 Remake",
        releaseYear: "2026", // يمكنك تعديل السنة إذا لزم الأمر
        translator: "علي العجيلي",
        appVersion: "v170775", // قم بتعديلها لنسخة اللعبة المتوافقة معك
        description:
          "تعريب شامل للعبة تقمص الأدوار الكلاسيكية المنتظرة Gothic 1 Remake. تم التركيز على ترجمة الحوارات العميقة، واجهة المستخدم، ووصف العناصر بدقة لضمان اندماجك الكامل في عالم اللعبة المظلم وتفاصيله.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط (7z) من الزر أدناه.",
          "استخدم برنامج 7-Zip أو WinRAR لفك الضغط عن الملف.",
          "انسخ جميع الملفات المستخرجة والصقها داخل المسار الرئيسي لتثبيت اللعبة.",
          "وافق على استبدال الملفات عند ظهور نافذة التأكيد.",
          "شغل اللعبة واستمتع بتجربة الـ RPG باللغة العربية!",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
        ], // 6 صور كما في المجلد
        technologies: ["توطين النصوص", "تعديل الخطوط"],
        downloadFile: "Gothic 1 Remake-Arabic-Patch.7z",
        addedDate: "2026-07-22",
      },
      {
        id: 4,
        folderName: "SpongeBob SquarePants Titans of the Tide",
        title: "SpongeBob SquarePants: Titans of the Tide",
        releaseYear: "2025",
        translator: "علي العجيلي",
        appVersion: "v1.4",
        description:
          "تعريب كامل وشامل للعبة المغامرات الممتعة SpongeBob SquarePants: Titans of the Tide. تم ترجمة الحوارات، القوائم، والنصوص بالكامل لضمان تجربة ممتعة ومفهومة لعشاق سبونج بوب بجميع الأعمار.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط (7z) من الزر أدناه.",
          "استخدم برنامج 7-Zip أو WinRAR لفك الضغط عن الملف.",
          "انسخ جميع الملفات الناتجة والصقها داخل مجلد تثبيت اللعبة الرئيسي.",
          "وافق على استبدال الملفات عند ظهور نافذة التأكيد.",
          "شغل اللعبة واستمتع بالمغامرة باللغة العربية!",
        ],
        coverImage: "poster.webp",
        screenshots: ["1.webp", "2.webp", "3.webp", "4.webp", "5.webp"],
        technologies: ["توطين النصوص", "تعديل الواجهة"],
        downloadFile:
          "SpongeBob SquarePants Titans of the Tide-Arabic-Patch.7z",
        addedDate: "2026-07-24",
      },
      {
        id: 5,
        folderName: "The Mound - Omen of Cthulhu",
        title: "The Mound - Omen of Cthulhu",
        releaseYear: "2026",
        translator: "علي العجيلي",
        appVersion: "v34308",
        description:
          "تعريب احترافي وشامل للعبة الرعب والغموض The Mound - Omen of Cthulhu. تم ترجمة القصة، الحوارات، والمستندات بدقة عالية لتعيش أجواء الرعب النفسي والقصص الغامضة بكل تفاصيلها بالعربية.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط (7z) من الزر أدناه.",
          "استخدم برنامج 7-Zip أو WinRAR لفك الضغط عن الملف.",
          "انسخ جميع الملفات الناتجة والصقها داخل مجلد تثبيت اللعبة الرئيسي.",
          "وافق على استبدال الملفات عند ظهور نافذة التأكيد.",
          "شغل اللعبة واستمتع بتجربة الرعب باللغة العربية!",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
        ],
        technologies: ["توطين النصوص", "تعديل الواجهة"],
        downloadFile: "The Mound Omen of Cthulhu-Arabic-Patch.7z",
        addedDate: "2026-07-29",
      },
      {
        id: 6,
        folderName: "Eriksholm - The Stolen Dream",
        title: "Eriksholm: The Stolen Dream",
        releaseYear: "2026",
        translator: "علي العجيلي",
        appVersion: "v1.4",
        description:
          "تعريب شامل للعبة التخفي والمغامرة Eriksholm: The Stolen Dream. يشمل التعريب ترجمة دقيقة للحوارات، القوائم، والنصوص لضمان اندماجك الكامل في عالم اللعبة وكشف أسرار مدينة إريكشهولم.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط (7z) من الزر أدناه.",
          "استخدم برنامج 7-Zip أو WinRAR لفك الضغط عن الملف.",
          "انسخ جميع الملفات المستخرجة والصقها داخل المسار الرئيسي لتثبيت اللعبة.",
          "وافق على استبدال الملفات عند ظهور نافذة التأكيد.",
          "شغل اللعبة واستمتع بالتجربة باللغة العربية!",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
        ],
        technologies: ["توطين النصوص", "تعديل الخطوط"],
        downloadFile: "Eriksholm - The Stolen Dream-Arabic-Patch.7z",
        addedDate: "2026-07-18",
      },
      {
        id: 7,
        folderName: "This Bed We Made",
        title: "This Bed We Made",
        releaseYear: "2023",
        translator: "علي العجيلي",
        appVersion: "v1.5.2",
        description:
          "تعريب احترافي وشامل للعبة التحقيق والغموض This Bed We Made. تدور أحداث القصة في خمسينيات القرن الماضي حول خادمة في فندق ترتدي ثوب التحقيق لكشف الأسرار، والتعريب يغطي الحوارات، القوائم، والمستندات بالكامل.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط (7z) من الزر أدناه.",
          "استخدم برنامج 7-Zip أو WinRAR لفك الضغط عن الملف.",
          "انسخ جميع الملفات الناتجة والصقها داخل مجلد تثبيت اللعبة الرئيسي.",
          "وافق على استبدال الملفات عند ظهور نافذة التأكيد.",
          "شغل اللعبة واستمتع بتجربة التحقيق باللغة العربية!",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
          "7.webp",
        ],
        technologies: ["توطين النصوص", "تعديل الواجهة"],
        downloadFile: "This Bed We Made - Arabic.7z",
        addedDate: "2026-07-28",
      },
      {
        id: 8, // تأكد من تعديل الرقم ليكون التسلسل الصحيح في مصفوفتك
        folderName: "The Relic First Guardian",
        title: "The Relic: First Guardian",
        releaseYear: "2026", // يمكنك تحديث السنة إذا كانت متوفرة
        translator: "علي العجيلي",
        appVersion: "v1.0", // يمكنك كتابة رقم النسخة المتوافقة لاحقاً
        description:
          "لعبة The Relic: First Guardian هي لعبة تقمص أدوار وأكشن (ARPG) مظلمة ومحمومة تأخذ اللاعبين في رحلة ملحمية مليئة بالتحديات. تم تطويرها بواسطة استوديو Project Cloud Games ونشرها بواسطة Perp Games. التعريب يشمل ترجمة كاملة لجميع جداول النصوص (النطاقات، العناصر، الأسماء، المهام، الرونز والمهارات) لتوفير تجربة ممتعة وواضحة.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط (rar) من الزر أدناه.",
          "استخدم برنامج WinRAR لفك الضغط واستخراج الملفات: zArabic_P.pak و zArabic_P.ucas و zArabic_P.utoc.",
          "توجه إلى مسار تثبيت اللعبة الأساسي، وادخل إلى المسار التالي: ProjectCloudGame\\Content\\Paks\\",
          'قم بإنشاء مجلد جديد باسم "~mods" داخل مجلد الـ Paks (إذا لم يكن موجوداً مسبقاً).',
          'انسخ ملفات التعريب الثلاثة والصقها داخل مجلد "~mods".',
          "شغل اللعبة واستمتع! (ملاحظة: لإلغاء التعريب والعودة للغة الأصلية، فقط قم بحذف هذه الملفات من المجلد).",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
          "7.webp",
        ],
        technologies: ["توطين النصوص", "تعديل الواجهة"],
        downloadFile: "The Relic First Guardian (Arabic).rar",
        addedDate: "2026-08-05",
      },
      {
        id: 9, // تأكد من تعديل الرقم التسلسلي ليكون التالي في مصفوفتك
        folderName: "Beast of Reincarnation",
        title: "Beast of Reincarnation",
        releaseYear: "2026",
        translator: "علي العجيلي",
        appVersion: "v1.0.7.0",
        description:
          "تعريب شامل للعبة Beast of Reincarnation، يغطي ترجمة القوائم، الحوارات، والنصوص الداخلية بالكامل لتوفير تجربة استثنائية وممتعة للاعب العربي.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط (7z) من الزر أدناه.",
          "استخرج الملفات باستخدام أحد برامج فك الضغط (مثل 7-Zip أو WinRAR).",
          "توجه إلى مسار تثبيت اللعبة الأساسي وضع ملفات التعريب في المجلد المخصص للمودز (Mods) الخاص باللعبة.",
          "شغل اللعبة واستمتع بالتعريب بالكامل.",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
          "7.webp",
        ],
        technologies: ["توطين النصوص", "تعريب القوائم"],
        downloadFile: "Beast of Reincarnation_v2.5_(Arabic).7z",
        addedDate: "2026-08-06",
      },
      {
        id: 10, // تأكد من تعديل الرقم التسلسلي ليكون التالي في مصفوفتك
        folderName: "Lost & Found - A This Bed We Made Story",
        title: "Lost & Found - A This Bed We Made Story",
        releaseYear: "2026",
        translator: "علي العجيلي",
        appVersion: "v6513",
        description:
          "تعريب شامل للقصة الفرعية Lost & Found - A This Bed We Made Story، يغطي ترجمة القوائم، الحوارات، والنصوص الداخلية بالكامل لتوفير تجربة استثنائية وممتعة للاعب العربي.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط (7z) من الزر أدناه.",
          "استخرج الملفات باستخدام أحد برامج فك الضغط (مثل 7-Zip أو WinRAR).",
          "توجه إلى مسار مجلد اللعبة الأساسي، وقم بلصق ملف التعريب داخل مجلد Paks عبر المسار: ThisBedWeMade\\Content\\Paks",
          "شغل اللعبة واستمتع بالتعريب بالكامل.",
        ],
        coverImage: "poster.webp",
        screenshots: ["1.webp", "2.webp", "3.webp", "4.webp", "5.webp"],
        technologies: ["توطين النصوص", "تعريب القوائم"],
        downloadFile: "Lost_and_Found_A_This_Bed_We_Made_Story_(Arabic).7z",
        addedDate: "2026-08-11",
      },
      {
        id: 11, // تأكد من تعديل الرقم التسلسلي ليكون التالي في مصفوفتك
        folderName: "Grounded 2",
        title: "Grounded 2",
        releaseYear: "2025",
        translator: "علي العجيلي",
        appVersion: "v0.1.1.1",
        description:
          "تعريب شامل للعبة Grounded 2، يغطي ترجمة القوائم، الحوارات، أسماء العناصر والأشياء، النصوص التعليمية، وواجهة المستخدم بالكامل، مع دعم الخط العربي وعرض الأرقام الغربية بشكل صحيح لتقديم تجربة متكاملة للاعب العربي.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط (7z) من الزر أدناه.",
          "استخرج الملفات باستخدام أحد برامج فك الضغط (مثل 7-Zip أو WinRAR).",
          "انسخ ملفات التعريب الثلاثة إلى مجلد Paks داخل مسار اللعبة: Augusta\\Content\\Paks",
          "شغل اللعبة واستمتع بالتعريب بالكامل.",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
          "7.webp",
        ],
        technologies: ["توطين النصوص", "تعريب القوائم", "دعم الخط العربي"],
        downloadFile: "Grounded_2_(Arabic).7z",
        addedDate: "2026-08-15",
      },
      {
        id: 12,
        folderName: "Men of War",
        title: "Men of War",
        releaseYear: "2009",
        translator: "علي العجيلي",
        appVersion: "v1.17.5",
        description:
          "تعريب عربي شامل للعبة Men of War إصدار 1.17.5، يشمل ترجمة القوائم، الحوارات، المهمات، التعليمات، رسائل التحميل، وأجزاء واجهة المستخدم، مع دعم كامل لعرض الحروف العربية واتجاه النصوص من اليمين إلى اليسار (RTL)، وخطوط عربية مخصصة وتحسين ترتيب الأسطر والنصوص الصغيرة. تم اختبار التعريب ويعمل بكفاءة على دقتي 720p و1080p.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط (7z) من الزر أدناه.",
          "استخرج الملفات باستخدام أحد برامج فك الضغط مثل 7-Zip أو WinRAR.",
          "افتح مجلد Mod ثم ادخل إلى Game_Root.",
          "انسخ جميع الملفات والمجلدات الموجودة داخل Game_Root فقط، ولا تنسخ مجلد Game_Root نفسه.",
          "الصق الملفات مباشرة داخل مجلد اللعبة الرئيسي الذي يحتوي على ملف mow.exe.",
          "عند ظهور رسالة دمج المجلدات أو استبدال الملفات، اختر Replace the files in the destination.",
          "شغل اللعبة واستمتع بتجربة Men of War باللغة العربية.",
          "لإزالة التعريب واستعادة الملفات الأصلية، افتح Original\\Game_Root وانسخ جميع محتوياته إلى مجلد اللعبة الرئيسي ثم وافق على استبدال الملفات.",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
          "7.webp",
        ],
        technologies: [
          "توطين النصوص",
          "تعريب القوائم والحوارات",
          "دعم RTL",
          "الخط العربي المخصص",
          "معالجة النصوص متعددة الأسطر",
          "تحسين واجهة المستخدم",
        ],
        downloadFile: "Men_of_War_Arabic.7z",
        addedDate: "2026-08-16",
      },
      {
        id: 13,
        folderName: "Jagged Alliance 3",
        title: "Jagged Alliance 3",
        releaseYear: "2023",
        translator: "علي العجيلي",
        appVersion: "v1.0",
        description:
          "تعريب عربي شامل للعبة Jagged Alliance 3 يعمل من خلال نظام المودات الرسمي للعبة دون تعديل ملفات اللعبة الأصلية. يشمل التعريب القوائم والواجهات والحوارات والنصوص الداخلية، مع دعم عرض اللغة العربية والخطوط العربية. تأتي الحزمة مع مثبت آلي يقوم بوضع مود JA3 Arabic Lab في المسار الصحيح تلقائيًا، بالإضافة إلى أدوات مستقلة لإزالة مود التعريب فقط أو حذف جميع المودات والعودة إلى حالة نظيفة.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط JA3_Arabic.rar من الزر أدناه.",
          "فك ضغط الحزمة باستخدام WinRAR أو 7-Zip.",
          "أغلق Jagged Alliance 3 بالكامل قبل بدء التثبيت.",
          "شغّل الملف INSTALL_ARABIC.bat الموجود داخل الحزمة.",
          "انتظر حتى تظهر رسالة INSTALLATION COMPLETE.",
          "شغّل Jagged Alliance 3 ثم افتح Mod Manager.",
          "فعّل المود JA3 Arabic Lab.",
          "إذا لم يظهر التعريب مباشرة، أغلق اللعبة ثم شغّلها مرة أخرى.",
          "لا تحتاج إلى نسخ أي ملفات داخل مجلد تثبيت اللعبة الأصلي، فالمثبت يضع المود تلقائيًا في %APPDATA%\\Jagged Alliance 3\\mods\\JA3 Arabic Lab.",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
          "7.webp",
        ],
        technologies: [
          "توطين النصوص",
          "تعريب القوائم والحوارات",
          "دعم الخط العربي",
          "نظام Mods",
          "مثبت آلي",
        ],
        downloadFile: "JA3_Arabic.rar",
        addedDate: "2026-08-24",
      },
      {
        id: 14,
        folderName: "Cursed Mountain",
        title: "Cursed Mountain",
        releaseYear: "2009",
        translator: "علي العجيلي",
        appVersion: "v1.0",
        description:
          "تعريب عربي شامل للعبة الرعب والمغامرات Cursed Mountain إلى العربية الفصحى. يغطي التعريب القوائم والواجهات والتعليمات وشروحات التحكم والحوارات والنصوص داخل اللعب وأوصاف العناصر والأدوات والكتب والملاحظات والأهداف ورسائل النظام، بالإضافة إلى ترجمة المقاطع السينمائية. يتضمن التعريب خطًا عربيًا مخصصًا ومثبتًا آليًا يتحقق من سلامة جميع الملفات المستهدفة باستخدام SHA-256 قبل إنشاء النسخة الاحتياطية أو تعديل ملفات اللعبة.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط Cursed_Mountain_Arabic.rar من الزر أدناه.",
          "فك ضغط الحزمة باستخدام WinRAR أو 7-Zip.",
          "شغّل الملف INSTALL_ARABIC.bat.",
          "عندما يطلب منك المثبت مسار اللعبة، أدخل مجلد Cursed Mountain الرئيسي، مثال: D:\\Games\\Cursed Mountain.",
          "سيقوم المثبت بفحص SHA-256 لجميع الملفات التي سيعدلها قبل إنشاء أي نسخة احتياطية.",
          "إذا كانت ملفات اللعبة أصلية، سيتم إنشاء نسخة احتياطية داخل Cursed_Mountain_Arabic_Backup_v1.0.",
          "بعد ذلك سيقوم المثبت بتثبيت التعريب والتحقق من الملفات مرة أخرى.",
          "شغّل اللعبة واستمتع بالتجربة باللغة العربية.",
          "لإزالة التعريب، شغّل REMOVE_ARABIC.bat وأدخل نفس مسار اللعبة ليتم التحقق من النسخة الاحتياطية الأصلية واستعادتها.",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
          "7.webp",
          "8.webp",
        ],
        technologies: [
          "توطين النصوص",
          "تعريب القوائم والحوارات",
          "دعم الخط العربي",
          "ترجمة المقاطع السينمائية",
          "مثبت آلي",
          "SHA-256",
        ],
        downloadFile: "Cursed_Mountain_Arabic.rar",
        addedDate: "2026-08-24",
      },
      {
        id: 15,
        folderName: "Help Will Come Tomorrow",
        title: "Help Will Come Tomorrow",
        releaseYear: "2020",
        translator: "علي العجيلي",
        appVersion: "v1.1.2",
        description:
          "تعريب عربي شامل للعبة البقاء والاستراتيجية Help Will Come Tomorrow، يشمل ترجمة القوائم والواجهات والحوارات والنصوص الداخلية والمعلومات المرتبطة بالشخصيات والأحداث، بهدف تقديم تجربة عربية متكاملة مع الحفاظ على أجواء اللعبة وقصتها.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط Help_Will_Come_Tomorrow_Arabic.7z من الزر أدناه.",
          "استخرج محتويات الحزمة باستخدام 7-Zip أو WinRAR.",
          "أغلق اللعبة بالكامل قبل تثبيت التعريب.",
          "اتبع تعليمات التثبيت الموجودة داخل حزمة التعريب.",
          "بعد اكتمال التثبيت، شغّل اللعبة واستمتع بالتجربة باللغة العربية.",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
          "7.webp",
          "8.webp",
        ],
        technologies: [
          "توطين النصوص",
          "تعريب القوائم والحوارات",
          "دعم اللغة العربية",
          "Unity",
        ],
        downloadFile: "Help_Will_Come_Tomorrow_Arabic.7z",
        addedDate: "2026-08-27",
      },
      {
        id: 16,
        folderName: "Kill The Shadow",
        title: "Kill The Shadow",
        releaseYear: "2026",
        translator: "علي العجيلي",
        appVersion: "v1.1.0",
        description:
          "تعريب عربي شامل للعبة التحقيق والغموض Kill The Shadow، متوافق مع Build 24925748، ويشمل ترجمة القوائم والواجهات والحوارات والنصوص الداخلية، مع دعم عرض اللغة العربية من اليمين إلى اليسار (RTL)، وخط عربي مخصص، ومعالجة التفاف الأسطر والعناوين الكبيرة، بالإضافة إلى تعريب الخرائط وعناوين المناطق وشاشات التحميل والشعارات والعناصر البصرية داخل اللعبة. تتضمن النسخة v1.1.0 تحديثات توافق وإصلاحات إضافية للعناصر البصرية وشاشات التحميل والخريطة والشعارات، مع اختبارات نهائية على نسخة نظيفة من اللعبة قبل النشر.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط Kill_The_Shadow_Arabic_v1.1.0_Build_24925748.zip من الزر أدناه.",
          "تأكد من أن نسختك من اللعبة متوافقة مع Build 24925748.",
          "استخرج محتويات الحزمة باستخدام 7-Zip أو WinRAR.",
          "أغلق اللعبة بالكامل قبل تثبيت التعريب.",
          "افتح مجلد Patch الموجود داخل حزمة التعريب.",
          "انسخ جميع الملفات والمجلدات الموجودة داخل مجلد Patch والصقها داخل مجلد اللعبة الرئيسي الذي يحتوي على ملف KillTheShadow.exe.",
          "وافق على دمج المجلدات واستبدال الملفات عند ظهور نافذة التأكيد.",
          "شغّل اللعبة، وإذا ظهر خيار اللغة فاختر اللغة الإنجليزية باعتبارها اللغة المستخدمة كأساس للتعريب العربي.",
          "لإزالة التعريب، استخدم خيار Verify integrity of game files في Steam أو استرجع الملفات الأصلية من نسخة احتياطية.",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
          "7.webp",
          "8.webp",
          "9.webp",
          "10.webp",
        ],
        technologies: [
          "توطين النصوص",
          "تعريب القوائم والحوارات",
          "دعم RTL",
          "الخط العربي المخصص",
          "معالجة التفاف النصوص",
          "تعريب الخرائط والعناصر البصرية",
          "تعريب شاشات التحميل",
          "تعريب الشعارات",
          "Unity",
        ],
        downloadUrl:
          "https://github.com/AliAl-ojeely/Arabic-L10-Hub/releases/download/v1.1.0/Kill_The_Shadow_Arabic_v1.1.0_Build_24925748.zip",
        addedDate: "2026-08-31",
      },
      {
        id: 17,
        folderName: "Stella of The End",
        title: "Stella of The End",
        releaseYear: "2022",
        translator: "علي العجيلي",
        appVersion: "v1.0.0",
        description:
          "تعريب عربي شامل للعبة الرواية البصرية Stella of The End، يتضمن ترجمة القصة والحوارات والقوائم والواجهات والإعدادات وشاشات الحفظ والتحميل ورسائل التأكيد والعناصر النصية المختلفة داخل اللعبة، مع دعم عرض اللغة العربية بصورة سليمة والمحافظة على أسلوب اللعبة وأجوائها الأصلية.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط Stella_of_The_End.7z من الزر أدناه.",
          "استخرج محتويات الحزمة باستخدام 7-Zip أو WinRAR.",
          "أغلق اللعبة بالكامل قبل تثبيت التعريب.",
          "اتبع تعليمات التثبيت الموجودة داخل حزمة التعريب وانسخ الملفات إلى مجلد اللعبة عند الطلب.",
          "بعد اكتمال التثبيت، شغّل اللعبة واختر اللغة الإنجليزية للاستفادة من التعريب العربي.",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
        ],
        technologies: [
          "توطين النصوص",
          "تعريب القوائم والحوارات",
          "تعريب واجهات المستخدم",
          "دعم اللغة العربية",
          "دعم RTL",
          "Artemis Engine",
          "PFS / PF8",
        ],
        downloadFile: "Stella_of_The_End.7z",
        addedDate: "2026-08-23",
      },
      {
        id: 18,
        folderName: "All Quiet in the Trenches",
        title: "All Quiet in the Trenches",
        releaseYear: "2024",
        translator: "علي العجيلي",
        appVersion: "v1.0.2",
        description:
          "تعريب عربي شامل للعبة All Quiet in the Trenches، متوافق مع نسخة اللعبة v0.12.2، ويتضمن ترجمة الحوارات والقصة واليوميات والقوائم والواجهات والإعدادات وشاشات التعليمات والخيارات والعناصر النصية المختلفة داخل اللعبة، مع دعم كامل لاتجاه RTL وتشكيل الحروف العربية والتفاف الأسطر ومعالجة علامات الترقيم والأرقام، بالإضافة إلى دمج خط Amiri وشعار عربي للعبة ومعالجة عرض التاريخ داخل اليوميات بصورة صحيحة.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط All_Quiet_in_the_Trenches_v1.0.2.rar من الزر أدناه.",
          "استخرج محتويات الحزمة باستخدام WinRAR أو 7-Zip.",
          "أغلق اللعبة بالكامل قبل تثبيت التعريب.",
          "انسخ مجلد All Quiet in the Trenches_Data الموجود داخل حزمة التعريب إلى مجلد اللعبة الرئيسي.",
          "عند ظهور رسالة الاستبدال في Windows اختر Replace the files in the destination لاستبدال الملفات المطلوبة.",
          "بعد اكتمال النسخ، شغّل اللعبة بشكل طبيعي من Steam واختر اللغة الإنجليزية للاستفادة من التعريب العربي.",
        ],
        coverImage: "poster.webp",
        screenshots: [
          "1.webp",
          "2.webp",
          "3.webp",
          "4.webp",
          "5.webp",
          "6.webp",
        ],
        technologies: [
          "توطين النصوص",
          "تعريب القوائم والحوارات",
          "تعريب اليوميات",
          "تعريب واجهات المستخدم",
          "دعم اللغة العربية",
          "دعم RTL",
          "Arabic Shaping",
          "TextMesh Pro",
          "Ink",
          "Unity",
          "Amiri Font",
        ],
        downloadUrl:
          "https://github.com/AliAl-ojeely/Arabic-L10-Hub/releases/download/all-quiet-in-the-trenches-ar-v1.0.2/All_Quiet_in_the_Trenches_v1.0.2.rar",
        addedDate: "2026-09-02",
      },
      {
        id: 19,
        folderName: "Banished",
        title: "Banished",
        releaseYear: "2014",
        translator: "علي العجيلي",
        appVersion: "v1.0.0",
        description:
          "تعريب عربي شامل للعبة Banished، متوافق مع نسخة اللعبة v1.0.7 Build 170910، ويتضمن تعريب 1,641 وحدة نصية تشمل القوائم والواجهات والنصوص الوصفية والمساعدة والدروس التعليمية ومختلف النصوص التي يدعمها نظام موارد اللعبة، مع معالجة اتصال وتشكيل الحروف العربية ودعم اتجاه RTL المرئي ودمج خط Amiri بأحجام محسنة للقراءة، بالإضافة إلى معالجة خاصة للنصوص الطويلة والتفاف الأسطر لمنع انقلاب ترتيب الأسطر العربية داخل واجهات اللعبة.",
        installationSteps: [
          "قم بتحميل ملف التعريب المضغوط Banished_Arabic_Localization_v1.0.0.7z من الزر أدناه.",
          "استخرج محتويات الحزمة باستخدام 7-Zip أو WinRAR.",
          "أغلق اللعبة بالكامل قبل تثبيت التعريب.",
          "انسخ محتويات الحزمة إلى مجلد لعبة Banished الرئيسي.",
          "تأكد من وجود ملف BanishedArabic.pkm داخل مجلد WinData.",
          "شغّل اللعبة وافتح قائمة Mods.",
          "فعّل Banished Arabic Translation ثم اضغط OK.",
          "وافق على إعادة تحميل موارد اللعبة إذا طلبت اللعبة ذلك، وبعدها سيعمل التعريب العربي.",
        ],
        coverImage: "poster.webp",
        screenshots: ["1.webp", "2.webp", "3.webp", "4.webp"],
        technologies: [
          "توطين النصوص",
          "تعريب القوائم والواجهات",
          "تعريب النصوص الوصفية",
          "تعريب المساعدة والدروس",
          "دعم اللغة العربية",
          "دعم RTL",
          "Arabic Shaping",
          "Amiri Font",
          "Auto Wrapping Fix",
          "PKM Mod",
          "Banished Modding",
        ],
        downloadUrl:
          "https://github.com/AliAl-ojeely/Arabic-L10-Hub/releases/download/banished-ar-v1.0.1/Banished_Arabic_Localization_v1.0.1.7z",
        addedDate: "2026-09-05",
        nexusModsUrl: "https://www.nexusmods.com/banished/mods/148?published=1",
      },
    ];

    return data.map(item => new Translation(item));
};